### PR TITLE
Port to 1.12.2.

### PR DESCRIPTION
**Pull request by Digimasterhir0**
**[THIS PULL REQUEST IS WORK IN PROGRESS]**

Seems that your Better Sleeping mod was slightly abandoned and no work done here since February 2017, so I made a port to 1.12.2. Some players as me wanted to port it and play with this mod on 1.12.2.

Some notes: 
This PR pushes changes to master branch, create one for 1.10.2 to avoid troubles. (but still saved in master branch in my fork).
This is port with disabled deployment in build.gradle, because old ones isn't working properly for me and causing lots of errors, mostly with "config" thing. (feel free to ask for changes in your gradle file, if you need)
Also, check out PRs in Calendar API and FoxieLib repositories, because they need to play/build mod with Better Sleeping.

Some explanations of changes:
- Now bed have 16 variants and I added meta 14 to get back the red bed.
- Changed command methods, because old ones was renamed.
- worldObj was renamed to just world and addChatMessage was renamed to sendMessage.
- Fixed pack.mcmeta's version and now it's v3 and .lang file works fine.
- Built with Forge 14.23.5.2768 (to build or if you want to play with port, check out releases of my fork of FoxieLib and Calendar API)

If you do not want to push this port and upload it, can it be as unofficial port of Better Sleeping?
P.S. I'm slighty bad at English, so feel free to ask questions.

### CODE REVIEW

**Comment by CallMeFoxie** [comment]
Thanks!
However, have you tested this that all features work? Because there's actually a lot of changes between 1.10 and 1.12 of how sleeping works, last time I tried it more code had to be patched (I wonder if I still have it somewhere laying). That's why I never released 1.12 version.

I see no changes done to the ASM part, which is actually even code-forced to run only on 1.10.2.. so it definitely cannot work :)

**Comment by DenisMasterHerobrine** [comment]
> Thanks!
> However, have you tested this that all features work? Because there's actually a lot of changes between 1.10 and 1.12 of how sleeping works, last time I tried it more code had to be patched (I wonder if I still have it somewhere laying). That's why I never released 1.12 version.
> 
> I see no changes done to the ASM part, which is actually even code-forced to run only on 1.10.2.. so it definitely cannot work :)

Gonna test it again, but this worked fine, when I tested it, if something gets broken I'll mark it as Draft and continue work with this.

EDIT:  Tested sleeping in vanilla bed for now, tested /getenergy and /setenergy again, debuffs and buffs and it's working fine, after sleeping at bed, I gained 16-18k of energy.

EDIT2: Now I know, what you mean, you can't sleep at daytime, while your bar can go down and you can die. Making this Draft for now.

**Comment by Digimasterhir0** [comment]
Seems, that there's a lot of ASM changes required and this gets harder to port. I'm sorry bothering you with those PRs, I had been trying to look into ways to fix it, but they aren't worked. Closing this, because there still no idea what to do with this port. I left open PRs for FoxieLib and Calendar API, if you want to continue your mods.

**Comment by eksynn** [comment]
so how exactly do we get this port for 1.12.2?

**Pull request closed without merging**
